/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2024-5-5: 15h: 4m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
// ATSstatmpdec_void(statmp4) ;
ATSstatic()
atsvoid_t0ype
kmain_0() ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude_056_unsafe__int2ptr__1(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude_056_unsafe__int2ptr__1__1(atstkind_t0ype(atstype_int)) ;

/*
/home/rafael/Documents/learning/ats/unsafe_c/main.dats: 79(line=5, offs=5) -- 176(line=10, offs=6)
*/
/*
local: 
global: kmain_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
kmain_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/unsafe_c/main.dats: 79(line=5, offs=5) -- 176(line=10, offs=6)
*/
ATSINSflab(__patsflab_kmain_0):
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/unsafe_c/main.dats: 93(line=6, offs=3) -- 176(line=10, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/unsafe_c/main.dats: 114(line=7, offs=18) -- 133(line=7, offs=37)
*/
ATSINSmove(tmp1, ATSLIB_056_prelude_056_unsafe__int2ptr__1__1(ATSPMVi0nt(0x10000000))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/unsafe_c/main.dats: 168(line=9, offs=3) -- 176(line=10, offs=6)
*/
ATSINSmove_void(tmpret0, ATSPMVempty()) ;
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/unsafe_c/main.dats: 93(line=6, offs=3) -- 176(line=10, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [kmain_0] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/unsafe.dats: 1616(line=50, offs=8) -- 1648(line=50, offs=40)
*/
/*
local: 
global: int2ptr$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude_056_unsafe__int2ptr__1(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/unsafe.dats: 1609(line=50, offs=1) -- 1648(line=50, offs=40)
*/
ATSINSflab(__patsflab_int2ptr):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/unsafe.dats: 1622(line=50, offs=14) -- 1648(line=50, offs=40)
*/
ATSINSmove(tmpret2, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), ATSPMVcastfn(cast, atstkind_t0ype(atstype_intptr), arg0))) ;
ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__int2ptr__1] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/unsafe.dats: 1616(line=50, offs=8) -- 1648(line=50, offs=40)
*/
/*
local: 
global: int2ptr$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude_056_unsafe__int2ptr__1__1(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/unsafe.dats: 1609(line=50, offs=1) -- 1648(line=50, offs=40)
*/
ATSINSflab(__patsflab_int2ptr):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/unsafe.dats: 1622(line=50, offs=14) -- 1648(line=50, offs=40)
*/
ATSINSmove(tmpret2__1, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), ATSPMVcastfn(cast, atstkind_t0ype(atstype_intptr), arg0))) ;
ATSfunbody_end()
ATSreturn(tmpret2__1) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__int2ptr__1__1] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_rafael_057_Documents_057_learning_057_ats_057_unsafe_c_057_main_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_rafael_057_Documents_057_learning_057_ats_057_unsafe_c_057_main_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_rafael_057_Documents_057_learning_057_ats_057_unsafe_c_057_main_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_rafael_057_Documents_057_learning_057_ats_057_unsafe_c_057_main_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/unsafe_c/main.dats: 187(line=12, offs=10) -- 194(line=12, offs=17)
*/
ATSINSmove_void(statmp4, kmain_0()) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
