/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2024-4-30: 13h:20m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g1int2int_int_int)
ATSdyncst_mac(atspre_g1int_gt_int)
ATSdyncst_mac(atspre_g1int_sub_int)
ATSdyncst_mac(atspre_g1int_mul_int)
ATSdyncst_mac(atspre_print_string)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
ATSstatic()
atstkind_t0ype(atstype_int)
fact_0(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_0_void() ;
#endif // end of [QUALIFIED]

/*
/home/rafael/Documents/learning/ats/hello-world/main.dats: 339(line=16, offs=5) -- 541(line=24, offs=4)
*/
/*
local: fact_0$0(level=0)
global: fact_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
fact_0(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 339(line=16, offs=5) -- 541(line=24, offs=4)
*/
ATSINSflab(__patsflab_fact_0):
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 401(line=17, offs=6) -- 406(line=17, offs=11)
*/
ATSINSmove(tmp1, ATSLIB_056_prelude__gt_g1int_int__1__1(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 398(line=17, offs=3) -- 541(line=24, offs=4)
*/
ATSif(
tmp1
) ATSthen() {
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 412(line=17, offs=17) -- 504(line=22, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 443(line=18, offs=28) -- 448(line=18, offs=33)
*/
ATSINSmove(tmp7, atspre_g1int_sub_int(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 437(line=18, offs=22) -- 449(line=18, offs=34)
*/
ATSINSmove(tmp6, fact_0(tmp7)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 462(line=19, offs=13) -- 468(line=19, offs=19)
*/
ATSINSmove(tmpret0, atspre_g1int_mul_int(arg0, tmp6)) ;

/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 412(line=17, offs=17) -- 504(line=22, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 535(line=23, offs=20) -- 536(line=23, offs=21)
*/
ATSINSmove(tmpret0, ATSPMVi0nt(1)) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [fact_0] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12679(line=659, offs=3) -- 12718(line=659, offs=42)
*/
/*
local: 
global: gt_g1int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4643)
tmparg = S2Evar(tk(4643))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12664(line=658, offs=1) -- 12718(line=659, offs=42)
*/
ATSINSflab(__patsflab_gt_g1int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12705(line=659, offs=29) -- 12716(line=659, offs=40)
*/
ATSINSmove(tmp3, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4643))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12688(line=659, offs=12) -- 12718(line=659, offs=42)
*/
ATSINSmove(tmpret2, PMVtmpltcst(g1int_gt<S2Evar(tk(4643))>)(arg0, tmp3)) ;

ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [ATSLIB_056_prelude__gt_g1int_int__1] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12679(line=659, offs=3) -- 12718(line=659, offs=42)
*/
/*
local: 
global: gt_g1int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4643)
tmparg = S2Evar(tk(4643))
tmpsub = Some(tk(4643) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12664(line=658, offs=1) -- 12718(line=659, offs=42)
*/
ATSINSflab(__patsflab_gt_g1int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12705(line=659, offs=29) -- 12716(line=659, offs=40)
*/
ATSINSmove(tmp3__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12688(line=659, offs=12) -- 12718(line=659, offs=42)
*/
ATSINSmove(tmpret2__1, atspre_g1int_gt_int(arg0, tmp3__1)) ;

ATSfunbody_end()
ATSreturn(tmpret2__1) ;
} /* end of [ATSLIB_056_prelude__gt_g1int_int__1__1] */

/*
/home/rafael/Documents/learning/ats/hello-world/main.dats: 559(line=26, offs=17) -- 614(line=30, offs=6)
*/
/*
local: 
global: mainats_0_void$7$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_0_void()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret8) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 553(line=26, offs=11) -- 614(line=30, offs=6)
*/
ATSINSflab(__patsflab_main_0_void):
/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 567(line=27, offs=3) -- 614(line=30, offs=6)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 584(line=28, offs=14) -- 603(line=28, offs=33)
*/
ATSINSmove_void(tmpret8, atspre_print_string(ATSPMVstring("Hello World"))) ;

/*
emit_instr: loc0 = /home/rafael/Documents/learning/ats/hello-world/main.dats: 567(line=27, offs=3) -- 614(line=30, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret8) ;
} /* end of [mainats_0_void] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_rafael_057_Documents_057_learning_057_ats_057_hello_055_world_057_main_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_rafael_057_Documents_057_learning_057_ats_057_hello_055_world_057_main_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_rafael_057_Documents_057_learning_057_ats_057_hello_055_world_057_main_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_rafael_057_Documents_057_learning_057_ats_057_hello_055_world_057_main_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_rafael_057_Documents_057_learning_057_ats_057_hello_055_world_057_main_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_rafael_057_Documents_057_learning_057_ats_057_hello_055_world_057_main_056_dats__dynload() ;
ATSmainats_0_void(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
